#!/bin/bash
# Parallel execution of orca may required to specify the absolute path to the binaries
# This is archived through this script :)
# modify path to orca binaries below and run as if you would call ORCA, e.g. "orca40 orca.in > orca.out"
ORCA=/usr/qc/orca_4_0_1_linux_x86-64/
$ORCA/orca $@
